using UnityEngine;

public class Player : MonoBehaviour
{
    [SerializeField] float velocidade = 10;
    [SerializeField] float teto = 468;
    [SerializeField] float ch達o = 32;
    [SerializeField] float parede = 960;
    
    void Start()
    {
        
    }

    void Update()
    {
        M達ozinhaMexer();
    }

    private void M達ozinhaMexer()
    {
        Vector2 input = new Vector2(Input.GetAxis("Horizontal"), Input.GetAxis("Vertical"));
        transform.position += new Vector3(input.x, input.y, 0) * velocidade * Time.deltaTime;
        transform.position = new Vector3 (transform.position.x, Mathf.Clamp(transform.position.y, ch達o, teto), 0);
        transform.position = new Vector3 (Mathf.Clamp(transform.position.x, 0, parede), transform.position.y, 0);
    }
}